# Introduction

Valleybike is a bike rental service with over 50 stations across the Pioneer Valley. Working with Wayne Feiden, we aimed to generate interesting insights about valleybike users and patterns of ridership from 2018 to 2020. With over 100,000 trips and 10,000 users, we worked with messy and large datasets to help answer three main questions of interest: (1) Where is the optimal location put new bike stations? (2) What does ridership and usage look like in low-income areas in the valley? (3) What kind of stories can be crafted in order to help obtain future sponsorships?

In order to answer those questions, we narrowed our analysis down to two main areas: riders and rides. We explored various ways to summarize trips through heatmaps and also extracted additional details such as stops that occurred during trips. In terms of learning more about users, we obtained basic demographic information about riders and used that to investigate whether certain characteristics were associated with particular riding patterns and habits. In this report we share our analysis process and results that were obtained. 